spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      keySerializer: "org.apache.kafka.common.serialization.StringSerializer"
      valueSerializer: "io.confluent.kafka.serializers.KafkaAvroSerializer"
      properties:
        schema:
          registry:
            url: "http://localhost:8081"
avro:
  topic:
    name: "spring.boot.stock.history.avro.topic.v1"
server:
  port: 8091
