server:
  port: 8092

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: "spring-boot-avro-consumer-id"
      keyDeserializer: "org.apache.kafka.common.serialization.StringDeserializer"
      valueDeserializer: "io.confluent.kafka.serializers.KafkaAvroDeserializer"
      autoOffsetReset: "earliest"
      properties:
        schema:
          registry:
            url: "http://localhost:8081"
        specific:
          avro:
            reader: "true"

avro:
  topic:
    name: "spring.boot.stock.history.avro.topic.v1"
